import { CountryCodeIsoAlpha2 } from '@/api/generated/smbdo.schemas';

type SubdivisionOption = { label: string; value: string };

/**
 * State/Province/Region subdivisions for supported countries.
 * Uses ISO 3166-2 subdivision codes (without country prefix) where applicable.
 *
 * Countries without entries here will fall back to a free-text input
 * for the state/province field.
 */
export const COUNTRY_SUBDIVISIONS: Partial<
  Record<CountryCodeIsoAlpha2, SubdivisionOption[]>
> = {
  // ── United States ────────────────────────────────────────────────
  US: [
    { label: 'Alabama', value: 'AL' },
    { label: 'Alaska', value: 'AK' },
    { label: 'Arizona', value: 'AZ' },
    { label: 'Arkansas', value: 'AR' },
    { label: 'California', value: 'CA' },
    { label: 'Colorado', value: 'CO' },
    { label: 'Connecticut', value: 'CT' },
    { label: 'Delaware', value: 'DE' },
    { label: 'District of Columbia', value: 'DC' },
    { label: 'Florida', value: 'FL' },
    { label: 'Georgia', value: 'GA' },
    { label: 'Hawaii', value: 'HI' },
    { label: 'Idaho', value: 'ID' },
    { label: 'Illinois', value: 'IL' },
    { label: 'Indiana', value: 'IN' },
    { label: 'Iowa', value: 'IA' },
    { label: 'Kansas', value: 'KS' },
    { label: 'Kentucky', value: 'KY' },
    { label: 'Louisiana', value: 'LA' },
    { label: 'Maine', value: 'ME' },
    { label: 'Maryland', value: 'MD' },
    { label: 'Massachusetts', value: 'MA' },
    { label: 'Michigan', value: 'MI' },
    { label: 'Minnesota', value: 'MN' },
    { label: 'Mississippi', value: 'MS' },
    { label: 'Missouri', value: 'MO' },
    { label: 'Montana', value: 'MT' },
    { label: 'Nebraska', value: 'NE' },
    { label: 'Nevada', value: 'NV' },
    { label: 'New Hampshire', value: 'NH' },
    { label: 'New Jersey', value: 'NJ' },
    { label: 'New Mexico', value: 'NM' },
    { label: 'New York', value: 'NY' },
    { label: 'North Carolina', value: 'NC' },
    { label: 'North Dakota', value: 'ND' },
    { label: 'Ohio', value: 'OH' },
    { label: 'Oklahoma', value: 'OK' },
    { label: 'Oregon', value: 'OR' },
    { label: 'Pennsylvania', value: 'PA' },
    { label: 'Rhode Island', value: 'RI' },
    { label: 'South Carolina', value: 'SC' },
    { label: 'South Dakota', value: 'SD' },
    { label: 'Tennessee', value: 'TN' },
    { label: 'Texas', value: 'TX' },
    { label: 'Utah', value: 'UT' },
    { label: 'Vermont', value: 'VT' },
    { label: 'Virginia', value: 'VA' },
    { label: 'Washington', value: 'WA' },
    { label: 'West Virginia', value: 'WV' },
    { label: 'Wisconsin', value: 'WI' },
    { label: 'Wyoming', value: 'WY' },
  ],

  // ── Canada ───────────────────────────────────────────────────────
  CA: [
    { label: 'Alberta', value: 'AB' },
    { label: 'British Columbia', value: 'BC' },
    { label: 'Manitoba', value: 'MB' },
    { label: 'New Brunswick', value: 'NB' },
    { label: 'Newfoundland and Labrador', value: 'NL' },
    { label: 'Northwest Territories', value: 'NT' },
    { label: 'Nova Scotia', value: 'NS' },
    { label: 'Nunavut', value: 'NU' },
    { label: 'Ontario', value: 'ON' },
    { label: 'Prince Edward Island', value: 'PE' },
    { label: 'Quebec', value: 'QC' },
    { label: 'Saskatchewan', value: 'SK' },
    { label: 'Yukon', value: 'YT' },
  ],

  // ── Australia ────────────────────────────────────────────────────
  AU: [
    { label: 'Australian Capital Territory', value: 'ACT' },
    { label: 'New South Wales', value: 'NSW' },
    { label: 'Northern Territory', value: 'NT' },
    { label: 'Queensland', value: 'QLD' },
    { label: 'South Australia', value: 'SA' },
    { label: 'Tasmania', value: 'TAS' },
    { label: 'Victoria', value: 'VIC' },
    { label: 'Western Australia', value: 'WA' },
  ],

  // ── United Kingdom ───────────────────────────────────────────────
  GB: [
    { label: 'England', value: 'ENG' },
    { label: 'Northern Ireland', value: 'NIR' },
    { label: 'Scotland', value: 'SCT' },
    { label: 'Wales', value: 'WLS' },
  ],

  // ── Germany ──────────────────────────────────────────────────────
  DE: [
    { label: 'Baden-Württemberg', value: 'BW' },
    { label: 'Bavaria', value: 'BY' },
    { label: 'Berlin', value: 'BE' },
    { label: 'Brandenburg', value: 'BB' },
    { label: 'Bremen', value: 'HB' },
    { label: 'Hamburg', value: 'HH' },
    { label: 'Hesse', value: 'HE' },
    { label: 'Lower Saxony', value: 'NI' },
    { label: 'Mecklenburg-Vorpommern', value: 'MV' },
    { label: 'North Rhine-Westphalia', value: 'NW' },
    { label: 'Rhineland-Palatinate', value: 'RP' },
    { label: 'Saarland', value: 'SL' },
    { label: 'Saxony', value: 'SN' },
    { label: 'Saxony-Anhalt', value: 'ST' },
    { label: 'Schleswig-Holstein', value: 'SH' },
    { label: 'Thuringia', value: 'TH' },
  ],

  // ── France ───────────────────────────────────────────────────────
  FR: [
    { label: 'Auvergne-Rhône-Alpes', value: 'ARA' },
    { label: 'Bourgogne-Franche-Comté', value: 'BFC' },
    { label: 'Bretagne', value: 'BRE' },
    { label: 'Centre-Val de Loire', value: 'CVL' },
    { label: 'Corse', value: 'COR' },
    { label: 'Grand Est', value: 'GES' },
    { label: 'Hauts-de-France', value: 'HDF' },
    { label: 'Île-de-France', value: 'IDF' },
    { label: 'Normandie', value: 'NOR' },
    { label: 'Nouvelle-Aquitaine', value: 'NAQ' },
    { label: 'Occitanie', value: 'OCC' },
    { label: 'Pays de la Loire', value: 'PDL' },
    { label: "Provence-Alpes-Côte d'Azur", value: 'PAC' },
  ],

  // ── Italy ────────────────────────────────────────────────────────
  IT: [
    { label: 'Abruzzo', value: '65' },
    { label: 'Basilicata', value: '77' },
    { label: 'Calabria', value: '78' },
    { label: 'Campania', value: '72' },
    { label: 'Emilia-Romagna', value: '45' },
    { label: 'Friuli Venezia Giulia', value: '36' },
    { label: 'Lazio', value: '62' },
    { label: 'Liguria', value: '42' },
    { label: 'Lombardia', value: '25' },
    { label: 'Marche', value: '57' },
    { label: 'Molise', value: '67' },
    { label: 'Piemonte', value: '21' },
    { label: 'Puglia', value: '75' },
    { label: 'Sardegna', value: '88' },
    { label: 'Sicilia', value: '82' },
    { label: 'Toscana', value: '52' },
    { label: 'Trentino-Alto Adige', value: '32' },
    { label: 'Umbria', value: '55' },
    { label: "Valle d'Aosta", value: '23' },
    { label: 'Veneto', value: '34' },
  ],

  // ── Spain ────────────────────────────────────────────────────────
  ES: [
    { label: 'Andalucía', value: 'AN' },
    { label: 'Aragón', value: 'AR' },
    { label: 'Asturias', value: 'AS' },
    { label: 'Canarias', value: 'CN' },
    { label: 'Cantabria', value: 'CB' },
    { label: 'Castilla y León', value: 'CL' },
    { label: 'Castilla-La Mancha', value: 'CM' },
    { label: 'Catalunya', value: 'CT' },
    { label: 'Ceuta', value: 'CE' },
    { label: 'Comunitat Valenciana', value: 'VC' },
    { label: 'Extremadura', value: 'EX' },
    { label: 'Galicia', value: 'GA' },
    { label: 'Illes Balears', value: 'IB' },
    { label: 'La Rioja', value: 'RI' },
    { label: 'Madrid', value: 'MD' },
    { label: 'Melilla', value: 'ML' },
    { label: 'Murcia', value: 'MC' },
    { label: 'Navarra', value: 'NC' },
    { label: 'País Vasco', value: 'PV' },
  ],

  // ── Brazil ───────────────────────────────────────────────────────
  BR: [
    { label: 'Acre', value: 'AC' },
    { label: 'Alagoas', value: 'AL' },
    { label: 'Amapá', value: 'AP' },
    { label: 'Amazonas', value: 'AM' },
    { label: 'Bahia', value: 'BA' },
    { label: 'Ceará', value: 'CE' },
    { label: 'Distrito Federal', value: 'DF' },
    { label: 'Espírito Santo', value: 'ES' },
    { label: 'Goiás', value: 'GO' },
    { label: 'Maranhão', value: 'MA' },
    { label: 'Mato Grosso', value: 'MT' },
    { label: 'Mato Grosso do Sul', value: 'MS' },
    { label: 'Minas Gerais', value: 'MG' },
    { label: 'Pará', value: 'PA' },
    { label: 'Paraíba', value: 'PB' },
    { label: 'Paraná', value: 'PR' },
    { label: 'Pernambuco', value: 'PE' },
    { label: 'Piauí', value: 'PI' },
    { label: 'Rio de Janeiro', value: 'RJ' },
    { label: 'Rio Grande do Norte', value: 'RN' },
    { label: 'Rio Grande do Sul', value: 'RS' },
    { label: 'Rondônia', value: 'RO' },
    { label: 'Roraima', value: 'RR' },
    { label: 'Santa Catarina', value: 'SC' },
    { label: 'São Paulo', value: 'SP' },
    { label: 'Sergipe', value: 'SE' },
    { label: 'Tocantins', value: 'TO' },
  ],

  // ── Mexico ───────────────────────────────────────────────────────
  MX: [
    { label: 'Aguascalientes', value: 'AGU' },
    { label: 'Baja California', value: 'BCN' },
    { label: 'Baja California Sur', value: 'BCS' },
    { label: 'Campeche', value: 'CAM' },
    { label: 'Chiapas', value: 'CHP' },
    { label: 'Chihuahua', value: 'CHH' },
    { label: 'Ciudad de México', value: 'CMX' },
    { label: 'Coahuila', value: 'COA' },
    { label: 'Colima', value: 'COL' },
    { label: 'Durango', value: 'DUR' },
    { label: 'Guanajuato', value: 'GUA' },
    { label: 'Guerrero', value: 'GRO' },
    { label: 'Hidalgo', value: 'HID' },
    { label: 'Jalisco', value: 'JAL' },
    { label: 'Estado de México', value: 'MEX' },
    { label: 'Michoacán', value: 'MIC' },
    { label: 'Morelos', value: 'MOR' },
    { label: 'Nayarit', value: 'NAY' },
    { label: 'Nuevo León', value: 'NLE' },
    { label: 'Oaxaca', value: 'OAX' },
    { label: 'Puebla', value: 'PUE' },
    { label: 'Querétaro', value: 'QUE' },
    { label: 'Quintana Roo', value: 'ROO' },
    { label: 'San Luis Potosí', value: 'SLP' },
    { label: 'Sinaloa', value: 'SIN' },
    { label: 'Sonora', value: 'SON' },
    { label: 'Tabasco', value: 'TAB' },
    { label: 'Tamaulipas', value: 'TAM' },
    { label: 'Tlaxcala', value: 'TLA' },
    { label: 'Veracruz', value: 'VER' },
    { label: 'Yucatán', value: 'YUC' },
    { label: 'Zacatecas', value: 'ZAC' },
  ],

  // ── India ────────────────────────────────────────────────────────
  IN: [
    { label: 'Andaman and Nicobar Islands', value: 'AN' },
    { label: 'Andhra Pradesh', value: 'AP' },
    { label: 'Arunachal Pradesh', value: 'AR' },
    { label: 'Assam', value: 'AS' },
    { label: 'Bihar', value: 'BR' },
    { label: 'Chandigarh', value: 'CH' },
    { label: 'Chhattisgarh', value: 'CG' },
    { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'DH' },
    { label: 'Delhi', value: 'DL' },
    { label: 'Goa', value: 'GA' },
    { label: 'Gujarat', value: 'GJ' },
    { label: 'Haryana', value: 'HR' },
    { label: 'Himachal Pradesh', value: 'HP' },
    { label: 'Jammu and Kashmir', value: 'JK' },
    { label: 'Jharkhand', value: 'JH' },
    { label: 'Karnataka', value: 'KA' },
    { label: 'Kerala', value: 'KL' },
    { label: 'Ladakh', value: 'LA' },
    { label: 'Lakshadweep', value: 'LD' },
    { label: 'Madhya Pradesh', value: 'MP' },
    { label: 'Maharashtra', value: 'MH' },
    { label: 'Manipur', value: 'MN' },
    { label: 'Meghalaya', value: 'ML' },
    { label: 'Mizoram', value: 'MZ' },
    { label: 'Nagaland', value: 'NL' },
    { label: 'Odisha', value: 'OD' },
    { label: 'Puducherry', value: 'PY' },
    { label: 'Punjab', value: 'PB' },
    { label: 'Rajasthan', value: 'RJ' },
    { label: 'Sikkim', value: 'SK' },
    { label: 'Tamil Nadu', value: 'TN' },
    { label: 'Telangana', value: 'TS' },
    { label: 'Tripura', value: 'TR' },
    { label: 'Uttar Pradesh', value: 'UP' },
    { label: 'Uttarakhand', value: 'UK' },
    { label: 'West Bengal', value: 'WB' },
  ],

  // ── Argentina ────────────────────────────────────────────────────
  AR: [
    { label: 'Buenos Aires', value: 'B' },
    { label: 'Catamarca', value: 'K' },
    { label: 'Chaco', value: 'H' },
    { label: 'Chubut', value: 'U' },
    { label: 'Ciudad Autónoma de Buenos Aires', value: 'C' },
    { label: 'Córdoba', value: 'X' },
    { label: 'Corrientes', value: 'W' },
    { label: 'Entre Ríos', value: 'E' },
    { label: 'Formosa', value: 'P' },
    { label: 'Jujuy', value: 'Y' },
    { label: 'La Pampa', value: 'L' },
    { label: 'La Rioja', value: 'F' },
    { label: 'Mendoza', value: 'M' },
    { label: 'Misiones', value: 'N' },
    { label: 'Neuquén', value: 'Q' },
    { label: 'Río Negro', value: 'R' },
    { label: 'Salta', value: 'A' },
    { label: 'San Juan', value: 'J' },
    { label: 'San Luis', value: 'D' },
    { label: 'Santa Cruz', value: 'Z' },
    { label: 'Santa Fe', value: 'S' },
    { label: 'Santiago del Estero', value: 'G' },
    { label: 'Tierra del Fuego', value: 'V' },
    { label: 'Tucumán', value: 'T' },
  ],

  // ── South Africa ─────────────────────────────────────────────────
  ZA: [
    { label: 'Eastern Cape', value: 'EC' },
    { label: 'Free State', value: 'FS' },
    { label: 'Gauteng', value: 'GP' },
    { label: 'KwaZulu-Natal', value: 'KZN' },
    { label: 'Limpopo', value: 'LP' },
    { label: 'Mpumalanga', value: 'MP' },
    { label: 'North West', value: 'NW' },
    { label: 'Northern Cape', value: 'NC' },
    { label: 'Western Cape', value: 'WC' },
  ],

  // ── New Zealand ──────────────────────────────────────────────────
  NZ: [
    { label: 'Auckland', value: 'AUK' },
    { label: 'Bay of Plenty', value: 'BOP' },
    { label: 'Canterbury', value: 'CAN' },
    { label: 'Gisborne', value: 'GIS' },
    { label: "Hawke's Bay", value: 'HKB' },
    { label: 'Manawatū-Whanganui', value: 'MWT' },
    { label: 'Marlborough', value: 'MBH' },
    { label: 'Nelson', value: 'NSN' },
    { label: 'Northland', value: 'NTL' },
    { label: 'Otago', value: 'OTA' },
    { label: 'Southland', value: 'STL' },
    { label: 'Taranaki', value: 'TKI' },
    { label: 'Tasman', value: 'TAS' },
    { label: 'Waikato', value: 'WKO' },
    { label: 'Wellington', value: 'WGN' },
    { label: 'West Coast', value: 'WTC' },
  ],

  // ── Japan ────────────────────────────────────────────────────────
  JP: [
    { label: 'Hokkaido', value: '01' },
    { label: 'Aomori', value: '02' },
    { label: 'Iwate', value: '03' },
    { label: 'Miyagi', value: '04' },
    { label: 'Akita', value: '05' },
    { label: 'Yamagata', value: '06' },
    { label: 'Fukushima', value: '07' },
    { label: 'Ibaraki', value: '08' },
    { label: 'Tochigi', value: '09' },
    { label: 'Gunma', value: '10' },
    { label: 'Saitama', value: '11' },
    { label: 'Chiba', value: '12' },
    { label: 'Tokyo', value: '13' },
    { label: 'Kanagawa', value: '14' },
    { label: 'Niigata', value: '15' },
    { label: 'Toyama', value: '16' },
    { label: 'Ishikawa', value: '17' },
    { label: 'Fukui', value: '18' },
    { label: 'Yamanashi', value: '19' },
    { label: 'Nagano', value: '20' },
    { label: 'Gifu', value: '21' },
    { label: 'Shizuoka', value: '22' },
    { label: 'Aichi', value: '23' },
    { label: 'Mie', value: '24' },
    { label: 'Shiga', value: '25' },
    { label: 'Kyoto', value: '26' },
    { label: 'Osaka', value: '27' },
    { label: 'Hyogo', value: '28' },
    { label: 'Nara', value: '29' },
    { label: 'Wakayama', value: '30' },
    { label: 'Tottori', value: '31' },
    { label: 'Shimane', value: '32' },
    { label: 'Okayama', value: '33' },
    { label: 'Hiroshima', value: '34' },
    { label: 'Yamaguchi', value: '35' },
    { label: 'Tokushima', value: '36' },
    { label: 'Kagawa', value: '37' },
    { label: 'Ehime', value: '38' },
    { label: 'Kochi', value: '39' },
    { label: 'Fukuoka', value: '40' },
    { label: 'Saga', value: '41' },
    { label: 'Nagasaki', value: '42' },
    { label: 'Kumamoto', value: '43' },
    { label: 'Oita', value: '44' },
    { label: 'Miyazaki', value: '45' },
    { label: 'Kagoshima', value: '46' },
    { label: 'Okinawa', value: '47' },
  ],

  // ── South Korea ──────────────────────────────────────────────────
  KR: [
    { label: 'Seoul', value: '11' },
    { label: 'Busan', value: '26' },
    { label: 'Daegu', value: '27' },
    { label: 'Incheon', value: '28' },
    { label: 'Gwangju', value: '29' },
    { label: 'Daejeon', value: '30' },
    { label: 'Ulsan', value: '31' },
    { label: 'Sejong', value: '36' },
    { label: 'Gyeonggi', value: '41' },
    { label: 'Gangwon', value: '42' },
    { label: 'Chungcheongbuk', value: '43' },
    { label: 'Chungcheongnam', value: '44' },
    { label: 'Jeollabuk', value: '45' },
    { label: 'Jeollanam', value: '46' },
    { label: 'Gyeongsangbuk', value: '47' },
    { label: 'Gyeongsangnam', value: '48' },
    { label: 'Jeju', value: '49' },
  ],

  // ── China ────────────────────────────────────────────────────────
  CN: [
    { label: 'Anhui', value: 'AH' },
    { label: 'Beijing', value: 'BJ' },
    { label: 'Chongqing', value: 'CQ' },
    { label: 'Fujian', value: 'FJ' },
    { label: 'Gansu', value: 'GS' },
    { label: 'Guangdong', value: 'GD' },
    { label: 'Guangxi', value: 'GX' },
    { label: 'Guizhou', value: 'GZ' },
    { label: 'Hainan', value: 'HI' },
    { label: 'Hebei', value: 'HE' },
    { label: 'Heilongjiang', value: 'HL' },
    { label: 'Henan', value: 'HA' },
    { label: 'Hubei', value: 'HB' },
    { label: 'Hunan', value: 'HN' },
    { label: 'Inner Mongolia', value: 'NM' },
    { label: 'Jiangsu', value: 'JS' },
    { label: 'Jiangxi', value: 'JX' },
    { label: 'Jilin', value: 'JL' },
    { label: 'Liaoning', value: 'LN' },
    { label: 'Ningxia', value: 'NX' },
    { label: 'Qinghai', value: 'QH' },
    { label: 'Shaanxi', value: 'SN' },
    { label: 'Shandong', value: 'SD' },
    { label: 'Shanghai', value: 'SH' },
    { label: 'Shanxi', value: 'SX' },
    { label: 'Sichuan', value: 'SC' },
    { label: 'Tianjin', value: 'TJ' },
    { label: 'Tibet', value: 'XZ' },
    { label: 'Xinjiang', value: 'XJ' },
    { label: 'Yunnan', value: 'YN' },
    { label: 'Zhejiang', value: 'ZJ' },
  ],

  // ── Switzerland ──────────────────────────────────────────────────
  CH: [
    { label: 'Aargau', value: 'AG' },
    { label: 'Appenzell Ausserrhoden', value: 'AR' },
    { label: 'Appenzell Innerrhoden', value: 'AI' },
    { label: 'Basel-Landschaft', value: 'BL' },
    { label: 'Basel-Stadt', value: 'BS' },
    { label: 'Bern', value: 'BE' },
    { label: 'Fribourg', value: 'FR' },
    { label: 'Genève', value: 'GE' },
    { label: 'Glarus', value: 'GL' },
    { label: 'Graubünden', value: 'GR' },
    { label: 'Jura', value: 'JU' },
    { label: 'Luzern', value: 'LU' },
    { label: 'Neuchâtel', value: 'NE' },
    { label: 'Nidwalden', value: 'NW' },
    { label: 'Obwalden', value: 'OW' },
    { label: 'Schaffhausen', value: 'SH' },
    { label: 'Schwyz', value: 'SZ' },
    { label: 'Solothurn', value: 'SO' },
    { label: 'St. Gallen', value: 'SG' },
    { label: 'Thurgau', value: 'TG' },
    { label: 'Ticino', value: 'TI' },
    { label: 'Uri', value: 'UR' },
    { label: 'Valais', value: 'VS' },
    { label: 'Vaud', value: 'VD' },
    { label: 'Zug', value: 'ZG' },
    { label: 'Zürich', value: 'ZH' },
  ],

  // ── Austria ──────────────────────────────────────────────────────
  AT: [
    { label: 'Burgenland', value: '1' },
    { label: 'Carinthia', value: '2' },
    { label: 'Lower Austria', value: '3' },
    { label: 'Salzburg', value: '5' },
    { label: 'Styria', value: '6' },
    { label: 'Tyrol', value: '7' },
    { label: 'Upper Austria', value: '4' },
    { label: 'Vienna', value: '9' },
    { label: 'Vorarlberg', value: '8' },
  ],

  // ── Poland ───────────────────────────────────────────────────────
  PL: [
    { label: 'Dolnośląskie', value: 'DS' },
    { label: 'Kujawsko-Pomorskie', value: 'KP' },
    { label: 'Lubelskie', value: 'LU' },
    { label: 'Lubuskie', value: 'LB' },
    { label: 'Łódzkie', value: 'LD' },
    { label: 'Małopolskie', value: 'MA' },
    { label: 'Mazowieckie', value: 'MZ' },
    { label: 'Opolskie', value: 'OP' },
    { label: 'Podkarpackie', value: 'PK' },
    { label: 'Podlaskie', value: 'PD' },
    { label: 'Pomorskie', value: 'PM' },
    { label: 'Śląskie', value: 'SL' },
    { label: 'Świętokrzyskie', value: 'SK' },
    { label: 'Warmińsko-Mazurskie', value: 'WN' },
    { label: 'Wielkopolskie', value: 'WP' },
    { label: 'Zachodniopomorskie', value: 'ZP' },
  ],

  // ── Belgium ──────────────────────────────────────────────────────
  BE: [
    { label: 'Antwerp', value: 'VAN' },
    { label: 'Brussels-Capital Region', value: 'BRU' },
    { label: 'East Flanders', value: 'VOV' },
    { label: 'Flemish Brabant', value: 'VBR' },
    { label: 'Hainaut', value: 'WHT' },
    { label: 'Liège', value: 'WLG' },
    { label: 'Limburg', value: 'VLI' },
    { label: 'Luxembourg', value: 'WLX' },
    { label: 'Namur', value: 'WNA' },
    { label: 'Walloon Brabant', value: 'WBR' },
    { label: 'West Flanders', value: 'VWV' },
  ],

  // ── Chile ────────────────────────────────────────────────────────
  CL: [
    { label: 'Arica y Parinacota', value: 'AP' },
    { label: 'Tarapacá', value: 'TA' },
    { label: 'Antofagasta', value: 'AN' },
    { label: 'Atacama', value: 'AT' },
    { label: 'Coquimbo', value: 'CO' },
    { label: 'Valparaíso', value: 'VS' },
    { label: 'Región Metropolitana de Santiago', value: 'RM' },
    { label: "O'Higgins", value: 'LI' },
    { label: 'Maule', value: 'ML' },
    { label: 'Ñuble', value: 'NB' },
    { label: 'Biobío', value: 'BI' },
    { label: 'Araucanía', value: 'AR' },
    { label: 'Los Ríos', value: 'LR' },
    { label: 'Los Lagos', value: 'LL' },
    { label: 'Aysén', value: 'AI' },
    { label: 'Magallanes', value: 'MA' },
  ],

  // ── Colombia ─────────────────────────────────────────────────────
  CO: [
    { label: 'Amazonas', value: 'AMA' },
    { label: 'Antioquia', value: 'ANT' },
    { label: 'Arauca', value: 'ARA' },
    { label: 'Atlántico', value: 'ATL' },
    { label: 'Bogotá D.C.', value: 'DC' },
    { label: 'Bolívar', value: 'BOL' },
    { label: 'Boyacá', value: 'BOY' },
    { label: 'Caldas', value: 'CAL' },
    { label: 'Caquetá', value: 'CAQ' },
    { label: 'Casanare', value: 'CAS' },
    { label: 'Cauca', value: 'CAU' },
    { label: 'Cesar', value: 'CES' },
    { label: 'Chocó', value: 'CHO' },
    { label: 'Córdoba', value: 'COR' },
    { label: 'Cundinamarca', value: 'CUN' },
    { label: 'Guainía', value: 'GUA' },
    { label: 'Guaviare', value: 'GUV' },
    { label: 'Huila', value: 'HUI' },
    { label: 'La Guajira', value: 'LAG' },
    { label: 'Magdalena', value: 'MAG' },
    { label: 'Meta', value: 'MET' },
    { label: 'Nariño', value: 'NAR' },
    { label: 'Norte de Santander', value: 'NSA' },
    { label: 'Putumayo', value: 'PUT' },
    { label: 'Quindío', value: 'QUI' },
    { label: 'Risaralda', value: 'RIS' },
    { label: 'San Andrés y Providencia', value: 'SAP' },
    { label: 'Santander', value: 'SAN' },
    { label: 'Sucre', value: 'SUC' },
    { label: 'Tolima', value: 'TOL' },
    { label: 'Valle del Cauca', value: 'VAC' },
    { label: 'Vaupés', value: 'VAU' },
    { label: 'Vichada', value: 'VID' },
  ],

  // ── Czech Republic ───────────────────────────────────────────────
  CZ: [
    { label: 'Praha (Prague)', value: '10' },
    { label: 'Středočeský kraj', value: '20' },
    { label: 'Jihočeský kraj', value: '31' },
    { label: 'Plzeňský kraj', value: '32' },
    { label: 'Karlovarský kraj', value: '41' },
    { label: 'Ústecký kraj', value: '42' },
    { label: 'Liberecký kraj', value: '51' },
    { label: 'Královéhradecký kraj', value: '52' },
    { label: 'Pardubický kraj', value: '53' },
    { label: 'Kraj Vysočina', value: '63' },
    { label: 'Jihomoravský kraj', value: '64' },
    { label: 'Olomoucký kraj', value: '71' },
    { label: 'Zlínský kraj', value: '72' },
    { label: 'Moravskoslezský kraj', value: '80' },
  ],

  // ── Denmark ──────────────────────────────────────────────────────
  DK: [
    { label: 'Hovedstaden', value: '84' },
    { label: 'Midtjylland', value: '82' },
    { label: 'Nordjylland', value: '81' },
    { label: 'Sjælland', value: '85' },
    { label: 'Syddanmark', value: '83' },
  ],

  // ── Finland ──────────────────────────────────────────────────────
  FI: [
    { label: 'Åland', value: '01' },
    { label: 'Etelä-Karjala', value: '02' },
    { label: 'Etelä-Pohjanmaa', value: '03' },
    { label: 'Etelä-Savo', value: '04' },
    { label: 'Kainuu', value: '05' },
    { label: 'Kanta-Häme', value: '06' },
    { label: 'Keski-Pohjanmaa', value: '07' },
    { label: 'Keski-Suomi', value: '08' },
    { label: 'Kymenlaakso', value: '09' },
    { label: 'Lappi', value: '10' },
    { label: 'Pirkanmaa', value: '11' },
    { label: 'Pohjanmaa', value: '12' },
    { label: 'Pohjois-Karjala', value: '13' },
    { label: 'Pohjois-Pohjanmaa', value: '14' },
    { label: 'Pohjois-Savo', value: '15' },
    { label: 'Päijät-Häme', value: '16' },
    { label: 'Satakunta', value: '17' },
    { label: 'Uusimaa', value: '18' },
    { label: 'Varsinais-Suomi', value: '19' },
  ],

  // ── Hungary ──────────────────────────────────────────────────────
  HU: [
    { label: 'Bács-Kiskun', value: 'BK' },
    { label: 'Baranya', value: 'BA' },
    { label: 'Békés', value: 'BE' },
    { label: 'Borsod-Abaúj-Zemplén', value: 'BZ' },
    { label: 'Budapest', value: 'BU' },
    { label: 'Csongrád-Csanád', value: 'CS' },
    { label: 'Fejér', value: 'FE' },
    { label: 'Győr-Moson-Sopron', value: 'GS' },
    { label: 'Hajdú-Bihar', value: 'HB' },
    { label: 'Heves', value: 'HE' },
    { label: 'Jász-Nagykun-Szolnok', value: 'JN' },
    { label: 'Komárom-Esztergom', value: 'KE' },
    { label: 'Nógrád', value: 'NO' },
    { label: 'Pest', value: 'PE' },
    { label: 'Somogy', value: 'SO' },
    { label: 'Szabolcs-Szatmár-Bereg', value: 'SZ' },
    { label: 'Tolna', value: 'TO' },
    { label: 'Vas', value: 'VA' },
    { label: 'Veszprém', value: 'VE' },
    { label: 'Zala', value: 'ZA' },
  ],

  // ── Ireland ──────────────────────────────────────────────────────
  IE: [
    { label: 'Carlow', value: 'CW' },
    { label: 'Cavan', value: 'CN' },
    { label: 'Clare', value: 'CE' },
    { label: 'Cork', value: 'CO' },
    { label: 'Donegal', value: 'DL' },
    { label: 'Dublin', value: 'D' },
    { label: 'Galway', value: 'G' },
    { label: 'Kerry', value: 'KY' },
    { label: 'Kildare', value: 'KE' },
    { label: 'Kilkenny', value: 'KK' },
    { label: 'Laois', value: 'LS' },
    { label: 'Leitrim', value: 'LM' },
    { label: 'Limerick', value: 'LK' },
    { label: 'Longford', value: 'LD' },
    { label: 'Louth', value: 'LH' },
    { label: 'Mayo', value: 'MO' },
    { label: 'Meath', value: 'MH' },
    { label: 'Monaghan', value: 'MN' },
    { label: 'Offaly', value: 'OY' },
    { label: 'Roscommon', value: 'RN' },
    { label: 'Sligo', value: 'SO' },
    { label: 'Tipperary', value: 'TA' },
    { label: 'Waterford', value: 'WD' },
    { label: 'Westmeath', value: 'WH' },
    { label: 'Wexford', value: 'WX' },
    { label: 'Wicklow', value: 'WW' },
  ],

  // ── Israel ───────────────────────────────────────────────────────
  IL: [
    { label: 'Central (HaMerkaz)', value: 'M' },
    { label: 'Haifa', value: 'HA' },
    { label: 'Jerusalem', value: 'JM' },
    { label: 'Northern (HaTzafon)', value: 'Z' },
    { label: 'Southern (HaDarom)', value: 'D' },
    { label: 'Tel Aviv', value: 'TA' },
  ],

  // ── Netherlands ──────────────────────────────────────────────────
  NL: [
    { label: 'Drenthe', value: 'DR' },
    { label: 'Flevoland', value: 'FL' },
    { label: 'Fryslân', value: 'FR' },
    { label: 'Gelderland', value: 'GE' },
    { label: 'Groningen', value: 'GR' },
    { label: 'Limburg', value: 'LI' },
    { label: 'Noord-Brabant', value: 'NB' },
    { label: 'Noord-Holland', value: 'NH' },
    { label: 'Overijssel', value: 'OV' },
    { label: 'Utrecht', value: 'UT' },
    { label: 'Zeeland', value: 'ZE' },
    { label: 'Zuid-Holland', value: 'ZH' },
  ],

  // ── Norway ───────────────────────────────────────────────────────
  NO: [
    { label: 'Agder', value: '42' },
    { label: 'Innlandet', value: '34' },
    { label: 'Møre og Romsdal', value: '15' },
    { label: 'Nordland', value: '18' },
    { label: 'Oslo', value: '03' },
    { label: 'Rogaland', value: '11' },
    { label: 'Troms og Finnmark', value: '54' },
    { label: 'Trøndelag', value: '50' },
    { label: 'Vestfold og Telemark', value: '38' },
    { label: 'Vestland', value: '46' },
    { label: 'Viken', value: '30' },
  ],

  // ── Peru ─────────────────────────────────────────────────────────
  PE: [
    { label: 'Amazonas', value: 'AMA' },
    { label: 'Áncash', value: 'ANC' },
    { label: 'Apurímac', value: 'APU' },
    { label: 'Arequipa', value: 'ARE' },
    { label: 'Ayacucho', value: 'AYA' },
    { label: 'Cajamarca', value: 'CAJ' },
    { label: 'Callao', value: 'CAL' },
    { label: 'Cusco', value: 'CUS' },
    { label: 'Huancavelica', value: 'HUV' },
    { label: 'Huánuco', value: 'HUC' },
    { label: 'Ica', value: 'ICA' },
    { label: 'Junín', value: 'JUN' },
    { label: 'La Libertad', value: 'LAL' },
    { label: 'Lambayeque', value: 'LAM' },
    { label: 'Lima', value: 'LIM' },
    { label: 'Lima Provincia', value: 'LMA' },
    { label: 'Loreto', value: 'LOR' },
    { label: 'Madre de Dios', value: 'MDD' },
    { label: 'Moquegua', value: 'MOQ' },
    { label: 'Pasco', value: 'PAS' },
    { label: 'Piura', value: 'PIU' },
    { label: 'Puno', value: 'PUN' },
    { label: 'San Martín', value: 'SAM' },
    { label: 'Tacna', value: 'TAC' },
    { label: 'Tumbes', value: 'TUM' },
    { label: 'Ucayali', value: 'UCA' },
  ],

  // ── Portugal ─────────────────────────────────────────────────────
  PT: [
    { label: 'Aveiro', value: '01' },
    { label: 'Beja', value: '02' },
    { label: 'Braga', value: '03' },
    { label: 'Bragança', value: '04' },
    { label: 'Castelo Branco', value: '05' },
    { label: 'Coimbra', value: '06' },
    { label: 'Évora', value: '07' },
    { label: 'Faro', value: '08' },
    { label: 'Guarda', value: '09' },
    { label: 'Leiria', value: '10' },
    { label: 'Lisboa', value: '11' },
    { label: 'Portalegre', value: '12' },
    { label: 'Porto', value: '13' },
    { label: 'Santarém', value: '14' },
    { label: 'Setúbal', value: '15' },
    { label: 'Viana do Castelo', value: '16' },
    { label: 'Vila Real', value: '17' },
    { label: 'Viseu', value: '18' },
    { label: 'Açores', value: '20' },
    { label: 'Madeira', value: '30' },
  ],

  // ── Russia ───────────────────────────────────────────────────────
  RU: [
    { label: 'Adygea', value: 'AD' },
    { label: 'Altai Krai', value: 'ALT' },
    { label: 'Altai Republic', value: 'AL' },
    { label: 'Amur Oblast', value: 'AMU' },
    { label: 'Arkhangelsk Oblast', value: 'ARK' },
    { label: 'Astrakhan Oblast', value: 'AST' },
    { label: 'Bashkortostan', value: 'BA' },
    { label: 'Belgorod Oblast', value: 'BEL' },
    { label: 'Bryansk Oblast', value: 'BRY' },
    { label: 'Buryatia', value: 'BU' },
    { label: 'Chechen Republic', value: 'CE' },
    { label: 'Chelyabinsk Oblast', value: 'CHE' },
    { label: 'Chukotka', value: 'CHU' },
    { label: 'Chuvash Republic', value: 'CU' },
    { label: 'Dagestan', value: 'DA' },
    { label: 'Ingushetia', value: 'IN' },
    { label: 'Irkutsk Oblast', value: 'IRK' },
    { label: 'Ivanovo Oblast', value: 'IVA' },
    { label: 'Jewish Autonomous Oblast', value: 'YEV' },
    { label: 'Kabardino-Balkaria', value: 'KB' },
    { label: 'Kaliningrad Oblast', value: 'KGD' },
    { label: 'Kalmykia', value: 'KL' },
    { label: 'Kaluga Oblast', value: 'KLU' },
    { label: 'Kamchatka Krai', value: 'KAM' },
    { label: 'Karachay-Cherkessia', value: 'KC' },
    { label: 'Karelia', value: 'KR' },
    { label: 'Kemerovo Oblast', value: 'KEM' },
    { label: 'Khabarovsk Krai', value: 'KHA' },
    { label: 'Khakassia', value: 'KK' },
    { label: 'Khanty-Mansi', value: 'KHM' },
    { label: 'Kirov Oblast', value: 'KIR' },
    { label: 'Komi Republic', value: 'KO' },
    { label: 'Kostroma Oblast', value: 'KOS' },
    { label: 'Krasnodar Krai', value: 'KDA' },
    { label: 'Krasnoyarsk Krai', value: 'KYA' },
    { label: 'Kurgan Oblast', value: 'KGN' },
    { label: 'Kursk Oblast', value: 'KRS' },
    { label: 'Leningrad Oblast', value: 'LEN' },
    { label: 'Lipetsk Oblast', value: 'LIP' },
    { label: 'Magadan Oblast', value: 'MAG' },
    { label: 'Mari El', value: 'ME' },
    { label: 'Mordovia', value: 'MO' },
    { label: 'Moscow', value: 'MOW' },
    { label: 'Moscow Oblast', value: 'MOS' },
    { label: 'Murmansk Oblast', value: 'MUR' },
    { label: 'Nenets', value: 'NEN' },
    { label: 'Nizhny Novgorod Oblast', value: 'NIZ' },
    { label: 'North Ossetia–Alania', value: 'SE' },
    { label: 'Novgorod Oblast', value: 'NGR' },
    { label: 'Novosibirsk Oblast', value: 'NVS' },
    { label: 'Omsk Oblast', value: 'OMS' },
    { label: 'Orenburg Oblast', value: 'ORE' },
    { label: 'Oryol Oblast', value: 'ORL' },
    { label: 'Penza Oblast', value: 'PNZ' },
    { label: 'Perm Krai', value: 'PER' },
    { label: 'Primorsky Krai', value: 'PRI' },
    { label: 'Pskov Oblast', value: 'PSK' },
    { label: 'Rostov Oblast', value: 'ROS' },
    { label: 'Ryazan Oblast', value: 'RYA' },
    { label: 'Saint Petersburg', value: 'SPE' },
    { label: 'Sakha (Yakutia)', value: 'SA' },
    { label: 'Sakhalin Oblast', value: 'SAK' },
    { label: 'Samara Oblast', value: 'SAM' },
    { label: 'Saratov Oblast', value: 'SAR' },
    { label: 'Smolensk Oblast', value: 'SMO' },
    { label: 'Stavropol Krai', value: 'STA' },
    { label: 'Sverdlovsk Oblast', value: 'SVE' },
    { label: 'Tambov Oblast', value: 'TAM' },
    { label: 'Tatarstan', value: 'TT' },
    { label: 'Tomsk Oblast', value: 'TOM' },
    { label: 'Tula Oblast', value: 'TUL' },
    { label: 'Tuva', value: 'TY' },
    { label: 'Tver Oblast', value: 'TVE' },
    { label: 'Tyumen Oblast', value: 'TYU' },
    { label: 'Udmurt Republic', value: 'UD' },
    { label: 'Ulyanovsk Oblast', value: 'ULY' },
    { label: 'Vladimir Oblast', value: 'VLA' },
    { label: 'Volgograd Oblast', value: 'VGG' },
    { label: 'Vologda Oblast', value: 'VLG' },
    { label: 'Voronezh Oblast', value: 'VOR' },
    { label: 'Yamalo-Nenets', value: 'YAN' },
    { label: 'Yaroslavl Oblast', value: 'YAR' },
    { label: 'Zabaykalsky Krai', value: 'ZAB' },
  ],

  // ── Saudi Arabia ─────────────────────────────────────────────────
  SA: [
    { label: 'Al Bahah', value: '11' },
    { label: 'Al Jawf', value: '12' },
    { label: 'Al Qassim', value: '05' },
    { label: 'Asir', value: '14' },
    { label: 'Eastern Province', value: '04' },
    { label: "Ha'il", value: '06' },
    { label: 'Jazan', value: '09' },
    { label: 'Madinah', value: '03' },
    { label: 'Makkah', value: '02' },
    { label: 'Najran', value: '10' },
    { label: 'Northern Borders', value: '08' },
    { label: 'Riyadh', value: '01' },
    { label: 'Tabuk', value: '07' },
  ],

  // ── Sweden ───────────────────────────────────────────────────────
  SE: [
    { label: 'Blekinge', value: 'K' },
    { label: 'Dalarna', value: 'W' },
    { label: 'Gotland', value: 'I' },
    { label: 'Gävleborg', value: 'X' },
    { label: 'Halland', value: 'N' },
    { label: 'Jämtland', value: 'Z' },
    { label: 'Jönköping', value: 'F' },
    { label: 'Kalmar', value: 'H' },
    { label: 'Kronoberg', value: 'G' },
    { label: 'Norrbotten', value: 'BD' },
    { label: 'Skåne', value: 'M' },
    { label: 'Stockholm', value: 'AB' },
    { label: 'Södermanland', value: 'D' },
    { label: 'Uppsala', value: 'C' },
    { label: 'Värmland', value: 'S' },
    { label: 'Västerbotten', value: 'AC' },
    { label: 'Västernorrland', value: 'Y' },
    { label: 'Västmanland', value: 'U' },
    { label: 'Västra Götaland', value: 'O' },
    { label: 'Örebro', value: 'T' },
    { label: 'Östergötland', value: 'E' },
  ],

  // ── Turkey ───────────────────────────────────────────────────────
  TR: [
    { label: 'Adana', value: '01' },
    { label: 'Adıyaman', value: '02' },
    { label: 'Afyonkarahisar', value: '03' },
    { label: 'Ağrı', value: '04' },
    { label: 'Aksaray', value: '68' },
    { label: 'Amasya', value: '05' },
    { label: 'Ankara', value: '06' },
    { label: 'Antalya', value: '07' },
    { label: 'Ardahan', value: '75' },
    { label: 'Artvin', value: '08' },
    { label: 'Aydın', value: '09' },
    { label: 'Balıkesir', value: '10' },
    { label: 'Bartın', value: '74' },
    { label: 'Batman', value: '72' },
    { label: 'Bayburt', value: '69' },
    { label: 'Bilecik', value: '11' },
    { label: 'Bingöl', value: '12' },
    { label: 'Bitlis', value: '13' },
    { label: 'Bolu', value: '14' },
    { label: 'Burdur', value: '15' },
    { label: 'Bursa', value: '16' },
    { label: 'Çanakkale', value: '17' },
    { label: 'Çankırı', value: '18' },
    { label: 'Çorum', value: '19' },
    { label: 'Denizli', value: '20' },
    { label: 'Diyarbakır', value: '21' },
    { label: 'Düzce', value: '81' },
    { label: 'Edirne', value: '22' },
    { label: 'Elazığ', value: '23' },
    { label: 'Erzincan', value: '24' },
    { label: 'Erzurum', value: '25' },
    { label: 'Eskişehir', value: '26' },
    { label: 'Gaziantep', value: '27' },
    { label: 'Giresun', value: '28' },
    { label: 'Gümüşhane', value: '29' },
    { label: 'Hakkâri', value: '30' },
    { label: 'Hatay', value: '31' },
    { label: 'Iğdır', value: '76' },
    { label: 'Isparta', value: '32' },
    { label: 'İstanbul', value: '34' },
    { label: 'İzmir', value: '35' },
    { label: 'Kahramanmaraş', value: '46' },
    { label: 'Karabük', value: '78' },
    { label: 'Karaman', value: '70' },
    { label: 'Kars', value: '36' },
    { label: 'Kastamonu', value: '37' },
    { label: 'Kayseri', value: '38' },
    { label: 'Kilis', value: '79' },
    { label: 'Kırıkkale', value: '71' },
    { label: 'Kırklareli', value: '39' },
    { label: 'Kırşehir', value: '40' },
    { label: 'Kocaeli', value: '41' },
    { label: 'Konya', value: '42' },
    { label: 'Kütahya', value: '43' },
    { label: 'Malatya', value: '44' },
    { label: 'Manisa', value: '45' },
    { label: 'Mardin', value: '47' },
    { label: 'Mersin', value: '33' },
    { label: 'Muğla', value: '48' },
    { label: 'Muş', value: '49' },
    { label: 'Nevşehir', value: '50' },
    { label: 'Niğde', value: '51' },
    { label: 'Ordu', value: '52' },
    { label: 'Osmaniye', value: '80' },
    { label: 'Rize', value: '53' },
    { label: 'Sakarya', value: '54' },
    { label: 'Samsun', value: '55' },
    { label: 'Şanlıurfa', value: '63' },
    { label: 'Siirt', value: '56' },
    { label: 'Sinop', value: '57' },
    { label: 'Şırnak', value: '73' },
    { label: 'Sivas', value: '58' },
    { label: 'Tekirdağ', value: '59' },
    { label: 'Tokat', value: '60' },
    { label: 'Trabzon', value: '61' },
    { label: 'Tunceli', value: '62' },
    { label: 'Uşak', value: '64' },
    { label: 'Van', value: '65' },
    { label: 'Yalova', value: '77' },
    { label: 'Yozgat', value: '66' },
    { label: 'Zonguldak', value: '67' },
  ],

  // ── Ecuador ──────────────────────────────────────────────────────
  EC: [
    { label: 'Azuay', value: 'A' },
    { label: 'Bolívar', value: 'B' },
    { label: 'Cañar', value: 'F' },
    { label: 'Carchi', value: 'C' },
    { label: 'Chimborazo', value: 'H' },
    { label: 'Cotopaxi', value: 'X' },
    { label: 'El Oro', value: 'O' },
    { label: 'Esmeraldas', value: 'E' },
    { label: 'Galápagos', value: 'W' },
    { label: 'Guayas', value: 'G' },
    { label: 'Imbabura', value: 'I' },
    { label: 'Loja', value: 'L' },
    { label: 'Los Ríos', value: 'R' },
    { label: 'Manabí', value: 'M' },
    { label: 'Morona Santiago', value: 'S' },
    { label: 'Napo', value: 'N' },
    { label: 'Orellana', value: 'D' },
    { label: 'Pastaza', value: 'Y' },
    { label: 'Pichincha', value: 'P' },
    { label: 'Santa Elena', value: 'SE' },
    { label: 'Santo Domingo de los Tsáchilas', value: 'SD' },
    { label: 'Sucumbíos', value: 'U' },
    { label: 'Tungurahua', value: 'T' },
    { label: 'Zamora Chinchipe', value: 'Z' },
  ],

  // ── Hong Kong ────────────────────────────────────────────────────
  HK: [
    { label: 'Central and Western', value: 'HCW' },
    { label: 'Eastern', value: 'HEA' },
    { label: 'Islands', value: 'NIS' },
    { label: 'Kowloon City', value: 'KKC' },
    { label: 'Kwai Tsing', value: 'NKT' },
    { label: 'Kwun Tong', value: 'KKT' },
    { label: 'North', value: 'NNO' },
    { label: 'Sai Kung', value: 'NSK' },
    { label: 'Sha Tin', value: 'NST' },
    { label: 'Sham Shui Po', value: 'KSS' },
    { label: 'Southern', value: 'HSO' },
    { label: 'Tai Po', value: 'NTP' },
    { label: 'Tsuen Wan', value: 'NTW' },
    { label: 'Tuen Mun', value: 'NTM' },
    { label: 'Wan Chai', value: 'HWC' },
    { label: 'Wong Tai Sin', value: 'KWT' },
    { label: 'Yau Tsim Mong', value: 'KYT' },
    { label: 'Yuen Long', value: 'NYL' },
  ],

  // ── Singapore ────────────────────────────────────────────────────
  SG: [
    { label: 'Central Region', value: 'CR' },
    { label: 'East Region', value: 'ER' },
    { label: 'North Region', value: 'NR' },
    { label: 'North-East Region', value: 'NER' },
    { label: 'West Region', value: 'WR' },
  ],
};

/**
 * Returns the subdivision options for a given country code,
 * or undefined if that country doesn't have predefined subdivisions
 * (meaning the form should fall back to a free-text input).
 */
export function getSubdivisionsForCountry(
  countryCode: string | undefined
): SubdivisionOption[] | undefined {
  if (!countryCode) return undefined;
  return COUNTRY_SUBDIVISIONS[countryCode as CountryCodeIsoAlpha2];
}
