import { CountryCodeIsoAlpha2 } from '@/api/generated/smbdo.schemas';

type SubdivisionOption = { label: string; value: string };

/**
 * State/Province/Region subdivisions for supported countries.
 * Uses ISO 3166-2 subdivision codes (without country prefix) where applicable.
 *
 * Countries without entries here will fall back to a free-text input
 * for the state/province field.
 */
export const COUNTRY_SUBDIVISIONS: Partial<
  Record<CountryCodeIsoAlpha2, SubdivisionOption[]>
> = {
  // ── United States ────────────────────────────────────────────────
  US: [
    { label: 'Alabama', value: 'AL' },
    { label: 'Alaska', value: 'AK' },
    { label: 'Arizona', value: 'AZ' },
    { label: 'Arkansas', value: 'AR' },
    { label: 'California', value: 'CA' },
    { label: 'Colorado', value: 'CO' },
    { label: 'Connecticut', value: 'CT' },
    { label: 'Delaware', value: 'DE' },
    { label: 'District of Columbia', value: 'DC' },
    { label: 'Florida', value: 'FL' },
    { label: 'Georgia', value: 'GA' },
    { label: 'Hawaii', value: 'HI' },
    { label: 'Idaho', value: 'ID' },
    { label: 'Illinois', value: 'IL' },
    { label: 'Indiana', value: 'IN' },
    { label: 'Iowa', value: 'IA' },
    { label: 'Kansas', value: 'KS' },
    { label: 'Kentucky', value: 'KY' },
    { label: 'Louisiana', value: 'LA' },
    { label: 'Maine', value: 'ME' },
    { label: 'Maryland', value: 'MD' },
    { label: 'Massachusetts', value: 'MA' },
    { label: 'Michigan', value: 'MI' },
    { label: 'Minnesota', value: 'MN' },
    { label: 'Mississippi', value: 'MS' },
    { label: 'Missouri', value: 'MO' },
    { label: 'Montana', value: 'MT' },
    { label: 'Nebraska', value: 'NE' },
    { label: 'Nevada', value: 'NV' },
    { label: 'New Hampshire', value: 'NH' },
    { label: 'New Jersey', value: 'NJ' },
    { label: 'New Mexico', value: 'NM' },
    { label: 'New York', value: 'NY' },
    { label: 'North Carolina', value: 'NC' },
    { label: 'North Dakota', value: 'ND' },
    { label: 'Ohio', value: 'OH' },
    { label: 'Oklahoma', value: 'OK' },
    { label: 'Oregon', value: 'OR' },
    { label: 'Pennsylvania', value: 'PA' },
    { label: 'Rhode Island', value: 'RI' },
    { label: 'South Carolina', value: 'SC' },
    { label: 'South Dakota', value: 'SD' },
    { label: 'Tennessee', value: 'TN' },
    { label: 'Texas', value: 'TX' },
    { label: 'Utah', value: 'UT' },
    { label: 'Vermont', value: 'VT' },
    { label: 'Virginia', value: 'VA' },
    { label: 'Washington', value: 'WA' },
    { label: 'West Virginia', value: 'WV' },
    { label: 'Wisconsin', value: 'WI' },
    { label: 'Wyoming', value: 'WY' },
  ],

  // ── Canada ───────────────────────────────────────────────────────
  CA: [
    { label: 'Alberta', value: 'AB' },
    { label: 'British Columbia', value: 'BC' },
    { label: 'Manitoba', value: 'MB' },
    { label: 'New Brunswick', value: 'NB' },
    { label: 'Newfoundland and Labrador', value: 'NL' },
    { label: 'Northwest Territories', value: 'NT' },
    { label: 'Nova Scotia', value: 'NS' },
    { label: 'Nunavut', value: 'NU' },
    { label: 'Ontario', value: 'ON' },
    { label: 'Prince Edward Island', value: 'PE' },
    { label: 'Quebec', value: 'QC' },
    { label: 'Saskatchewan', value: 'SK' },
    { label: 'Yukon', value: 'YT' },
  ],

  // ── Australia ────────────────────────────────────────────────────
  AU: [
    { label: 'Australian Capital Territory', value: 'ACT' },
    { label: 'New South Wales', value: 'NSW' },
    { label: 'Northern Territory', value: 'NT' },
    { label: 'Queensland', value: 'QLD' },
    { label: 'South Australia', value: 'SA' },
    { label: 'Tasmania', value: 'TAS' },
    { label: 'Victoria', value: 'VIC' },
    { label: 'Western Australia', value: 'WA' },
  ],

  // ── United Kingdom ───────────────────────────────────────────────
  GB: [
    { label: 'England', value: 'ENG' },
    { label: 'Northern Ireland', value: 'NIR' },
    { label: 'Scotland', value: 'SCT' },
    { label: 'Wales', value: 'WLS' },
  ],

  // ── Germany ──────────────────────────────────────────────────────
  DE: [
    { label: 'Baden-Württemberg', value: 'BW' },
    { label: 'Bavaria', value: 'BY' },
    { label: 'Berlin', value: 'BE' },
    { label: 'Brandenburg', value: 'BB' },
    { label: 'Bremen', value: 'HB' },
    { label: 'Hamburg', value: 'HH' },
    { label: 'Hesse', value: 'HE' },
    { label: 'Lower Saxony', value: 'NI' },
    { label: 'Mecklenburg-Vorpommern', value: 'MV' },
    { label: 'North Rhine-Westphalia', value: 'NW' },
    { label: 'Rhineland-Palatinate', value: 'RP' },
    { label: 'Saarland', value: 'SL' },
    { label: 'Saxony', value: 'SN' },
    { label: 'Saxony-Anhalt', value: 'ST' },
    { label: 'Schleswig-Holstein', value: 'SH' },
    { label: 'Thuringia', value: 'TH' },
  ],

  // ── France ───────────────────────────────────────────────────────
  FR: [
    { label: 'Auvergne-Rhône-Alpes', value: 'ARA' },
    { label: 'Bourgogne-Franche-Comté', value: 'BFC' },
    { label: 'Bretagne', value: 'BRE' },
    { label: 'Centre-Val de Loire', value: 'CVL' },
    { label: 'Corse', value: 'COR' },
    { label: 'Grand Est', value: 'GES' },
    { label: 'Hauts-de-France', value: 'HDF' },
    { label: 'Île-de-France', value: 'IDF' },
    { label: 'Normandie', value: 'NOR' },
    { label: 'Nouvelle-Aquitaine', value: 'NAQ' },
    { label: 'Occitanie', value: 'OCC' },
    { label: 'Pays de la Loire', value: 'PDL' },
    { label: "Provence-Alpes-Côte d'Azur", value: 'PAC' },
  ],

  // ── Italy ────────────────────────────────────────────────────────
  IT: [
    { label: 'Abruzzo', value: 'ABR' },
    { label: 'Basilicata', value: 'BAS' },
    { label: 'Calabria', value: 'CAL' },
    { label: 'Campania', value: 'CAM' },
    { label: 'Emilia-Romagna', value: 'EMR' },
    { label: 'Friuli Venezia Giulia', value: 'FVG' },
    { label: 'Lazio', value: 'LAZ' },
    { label: 'Liguria', value: 'LIG' },
    { label: 'Lombardia', value: 'LOM' },
    { label: 'Marche', value: 'MAR' },
    { label: 'Molise', value: 'MOL' },
    { label: 'Piemonte', value: 'PMN' },
    { label: 'Puglia', value: 'PUG' },
    { label: 'Sardegna', value: 'SAR' },
    { label: 'Sicilia', value: 'SIC' },
    { label: 'Toscana', value: 'TOS' },
    { label: 'Trentino-Alto Adige', value: 'TAA' },
    { label: 'Umbria', value: 'UMB' },
    { label: "Valle d'Aosta", value: 'VDA' },
    { label: 'Veneto', value: 'VEN' },
  ],

  // ── Spain ────────────────────────────────────────────────────────
  ES: [
    { label: 'Andalucía', value: 'AN' },
    { label: 'Aragón', value: 'AR' },
    { label: 'Asturias', value: 'AS' },
    { label: 'Canarias', value: 'CN' },
    { label: 'Cantabria', value: 'CB' },
    { label: 'Castilla y León', value: 'CL' },
    { label: 'Castilla-La Mancha', value: 'CM' },
    { label: 'Catalunya', value: 'CT' },
    { label: 'Ceuta', value: 'CE' },
    { label: 'Comunitat Valenciana', value: 'VC' },
    { label: 'Extremadura', value: 'EX' },
    { label: 'Galicia', value: 'GA' },
    { label: 'Illes Balears', value: 'IB' },
    { label: 'La Rioja', value: 'RI' },
    { label: 'Madrid', value: 'MD' },
    { label: 'Melilla', value: 'ML' },
    { label: 'Murcia', value: 'MC' },
    { label: 'Navarra', value: 'NC' },
    { label: 'País Vasco', value: 'PV' },
  ],

  // ── Brazil ───────────────────────────────────────────────────────
  BR: [
    { label: 'Acre', value: 'AC' },
    { label: 'Alagoas', value: 'AL' },
    { label: 'Amapá', value: 'AP' },
    { label: 'Amazonas', value: 'AM' },
    { label: 'Bahia', value: 'BA' },
    { label: 'Ceará', value: 'CE' },
    { label: 'Distrito Federal', value: 'DF' },
    { label: 'Espírito Santo', value: 'ES' },
    { label: 'Goiás', value: 'GO' },
    { label: 'Maranhão', value: 'MA' },
    { label: 'Mato Grosso', value: 'MT' },
    { label: 'Mato Grosso do Sul', value: 'MS' },
    { label: 'Minas Gerais', value: 'MG' },
    { label: 'Pará', value: 'PA' },
    { label: 'Paraíba', value: 'PB' },
    { label: 'Paraná', value: 'PR' },
    { label: 'Pernambuco', value: 'PE' },
    { label: 'Piauí', value: 'PI' },
    { label: 'Rio de Janeiro', value: 'RJ' },
    { label: 'Rio Grande do Norte', value: 'RN' },
    { label: 'Rio Grande do Sul', value: 'RS' },
    { label: 'Rondônia', value: 'RO' },
    { label: 'Roraima', value: 'RR' },
    { label: 'Santa Catarina', value: 'SC' },
    { label: 'São Paulo', value: 'SP' },
    { label: 'Sergipe', value: 'SE' },
    { label: 'Tocantins', value: 'TO' },
  ],

  // ── Mexico ───────────────────────────────────────────────────────
  MX: [
    { label: 'Aguascalientes', value: 'AGU' },
    { label: 'Baja California', value: 'BCN' },
    { label: 'Baja California Sur', value: 'BCS' },
    { label: 'Campeche', value: 'CAM' },
    { label: 'Chiapas', value: 'CHP' },
    { label: 'Chihuahua', value: 'CHH' },
    { label: 'Ciudad de México', value: 'CMX' },
    { label: 'Coahuila', value: 'COA' },
    { label: 'Colima', value: 'COL' },
    { label: 'Durango', value: 'DUR' },
    { label: 'Guanajuato', value: 'GUA' },
    { label: 'Guerrero', value: 'GRO' },
    { label: 'Hidalgo', value: 'HID' },
    { label: 'Jalisco', value: 'JAL' },
    { label: 'Estado de México', value: 'MEX' },
    { label: 'Michoacán', value: 'MIC' },
    { label: 'Morelos', value: 'MOR' },
    { label: 'Nayarit', value: 'NAY' },
    { label: 'Nuevo León', value: 'NLE' },
    { label: 'Oaxaca', value: 'OAX' },
    { label: 'Puebla', value: 'PUE' },
    { label: 'Querétaro', value: 'QUE' },
    { label: 'Quintana Roo', value: 'ROO' },
    { label: 'San Luis Potosí', value: 'SLP' },
    { label: 'Sinaloa', value: 'SIN' },
    { label: 'Sonora', value: 'SON' },
    { label: 'Tabasco', value: 'TAB' },
    { label: 'Tamaulipas', value: 'TAM' },
    { label: 'Tlaxcala', value: 'TLA' },
    { label: 'Veracruz', value: 'VER' },
    { label: 'Yucatán', value: 'YUC' },
    { label: 'Zacatecas', value: 'ZAC' },
  ],

  // ── India ────────────────────────────────────────────────────────
  IN: [
    { label: 'Andaman and Nicobar Islands', value: 'AN' },
    { label: 'Andhra Pradesh', value: 'AP' },
    { label: 'Arunachal Pradesh', value: 'AR' },
    { label: 'Assam', value: 'AS' },
    { label: 'Bihar', value: 'BR' },
    { label: 'Chandigarh', value: 'CH' },
    { label: 'Chhattisgarh', value: 'CG' },
    { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'DD' },
    { label: 'Delhi', value: 'DL' },
    { label: 'Goa', value: 'GA' },
    { label: 'Gujarat', value: 'GJ' },
    { label: 'Haryana', value: 'HR' },
    { label: 'Himachal Pradesh', value: 'HP' },
    { label: 'Jammu and Kashmir', value: 'JK' },
    { label: 'Jharkhand', value: 'JH' },
    { label: 'Karnataka', value: 'KA' },
    { label: 'Kerala', value: 'KL' },
    { label: 'Ladakh', value: 'LA' },
    { label: 'Lakshadweep', value: 'LD' },
    { label: 'Madhya Pradesh', value: 'MP' },
    { label: 'Maharashtra', value: 'MH' },
    { label: 'Manipur', value: 'MN' },
    { label: 'Meghalaya', value: 'ML' },
    { label: 'Mizoram', value: 'MZ' },
    { label: 'Nagaland', value: 'NL' },
    { label: 'Odisha', value: 'OD' },
    { label: 'Puducherry', value: 'PY' },
    { label: 'Punjab', value: 'PB' },
    { label: 'Rajasthan', value: 'RJ' },
    { label: 'Sikkim', value: 'SK' },
    { label: 'Tamil Nadu', value: 'TN' },
    { label: 'Telangana', value: 'TS' },
    { label: 'Tripura', value: 'TR' },
    { label: 'Uttar Pradesh', value: 'UP' },
    { label: 'Uttarakhand', value: 'UK' },
    { label: 'West Bengal', value: 'WB' },
  ],

  // ── Argentina ────────────────────────────────────────────────────
  AR: [
    { label: 'Buenos Aires', value: 'B' },
    { label: 'Catamarca', value: 'K' },
    { label: 'Chaco', value: 'H' },
    { label: 'Chubut', value: 'U' },
    { label: 'Ciudad Autónoma de Buenos Aires', value: 'C' },
    { label: 'Córdoba', value: 'X' },
    { label: 'Corrientes', value: 'W' },
    { label: 'Entre Ríos', value: 'E' },
    { label: 'Formosa', value: 'P' },
    { label: 'Jujuy', value: 'Y' },
    { label: 'La Pampa', value: 'L' },
    { label: 'La Rioja', value: 'F' },
    { label: 'Mendoza', value: 'M' },
    { label: 'Misiones', value: 'N' },
    { label: 'Neuquén', value: 'Q' },
    { label: 'Río Negro', value: 'R' },
    { label: 'Salta', value: 'A' },
    { label: 'San Juan', value: 'J' },
    { label: 'San Luis', value: 'D' },
    { label: 'Santa Cruz', value: 'Z' },
    { label: 'Santa Fe', value: 'S' },
    { label: 'Santiago del Estero', value: 'G' },
    { label: 'Tierra del Fuego', value: 'V' },
    { label: 'Tucumán', value: 'T' },
  ],

  // ── South Africa ─────────────────────────────────────────────────
  ZA: [
    { label: 'Eastern Cape', value: 'EC' },
    { label: 'Free State', value: 'FS' },
    { label: 'Gauteng', value: 'GP' },
    { label: 'KwaZulu-Natal', value: 'KZN' },
    { label: 'Limpopo', value: 'LP' },
    { label: 'Mpumalanga', value: 'MP' },
    { label: 'North West', value: 'NW' },
    { label: 'Northern Cape', value: 'NC' },
    { label: 'Western Cape', value: 'WC' },
  ],

  // ── New Zealand ──────────────────────────────────────────────────
  NZ: [
    { label: 'Auckland', value: 'AUK' },
    { label: 'Bay of Plenty', value: 'BOP' },
    { label: 'Canterbury', value: 'CAN' },
    { label: 'Gisborne', value: 'GIS' },
    { label: "Hawke's Bay", value: 'HKB' },
    { label: 'Manawatū-Whanganui', value: 'MWT' },
    { label: 'Marlborough', value: 'MBH' },
    { label: 'Nelson', value: 'NSN' },
    { label: 'Northland', value: 'NTL' },
    { label: 'Otago', value: 'OTA' },
    { label: 'Southland', value: 'STL' },
    { label: 'Taranaki', value: 'TKI' },
    { label: 'Tasman', value: 'TAS' },
    { label: 'Waikato', value: 'WKO' },
    { label: 'Wellington', value: 'WGN' },
    { label: 'West Coast', value: 'WTC' },
  ],

  // ── Japan ────────────────────────────────────────────────────────
  JP: [
    { label: 'Hokkaido', value: '01' },
    { label: 'Aomori', value: '02' },
    { label: 'Iwate', value: '03' },
    { label: 'Miyagi', value: '04' },
    { label: 'Akita', value: '05' },
    { label: 'Yamagata', value: '06' },
    { label: 'Fukushima', value: '07' },
    { label: 'Ibaraki', value: '08' },
    { label: 'Tochigi', value: '09' },
    { label: 'Gunma', value: '10' },
    { label: 'Saitama', value: '11' },
    { label: 'Chiba', value: '12' },
    { label: 'Tokyo', value: '13' },
    { label: 'Kanagawa', value: '14' },
    { label: 'Niigata', value: '15' },
    { label: 'Toyama', value: '16' },
    { label: 'Ishikawa', value: '17' },
    { label: 'Fukui', value: '18' },
    { label: 'Yamanashi', value: '19' },
    { label: 'Nagano', value: '20' },
    { label: 'Gifu', value: '21' },
    { label: 'Shizuoka', value: '22' },
    { label: 'Aichi', value: '23' },
    { label: 'Mie', value: '24' },
    { label: 'Shiga', value: '25' },
    { label: 'Kyoto', value: '26' },
    { label: 'Osaka', value: '27' },
    { label: 'Hyogo', value: '28' },
    { label: 'Nara', value: '29' },
    { label: 'Wakayama', value: '30' },
    { label: 'Tottori', value: '31' },
    { label: 'Shimane', value: '32' },
    { label: 'Okayama', value: '33' },
    { label: 'Hiroshima', value: '34' },
    { label: 'Yamaguchi', value: '35' },
    { label: 'Tokushima', value: '36' },
    { label: 'Kagawa', value: '37' },
    { label: 'Ehime', value: '38' },
    { label: 'Kochi', value: '39' },
    { label: 'Fukuoka', value: '40' },
    { label: 'Saga', value: '41' },
    { label: 'Nagasaki', value: '42' },
    { label: 'Kumamoto', value: '43' },
    { label: 'Oita', value: '44' },
    { label: 'Miyazaki', value: '45' },
    { label: 'Kagoshima', value: '46' },
    { label: 'Okinawa', value: '47' },
  ],

  // ── South Korea ──────────────────────────────────────────────────
  KR: [
    { label: 'Seoul', value: '11' },
    { label: 'Busan', value: '26' },
    { label: 'Daegu', value: '27' },
    { label: 'Incheon', value: '28' },
    { label: 'Gwangju', value: '29' },
    { label: 'Daejeon', value: '30' },
    { label: 'Ulsan', value: '31' },
    { label: 'Sejong', value: '36' },
    { label: 'Gyeonggi', value: '41' },
    { label: 'Gangwon', value: '42' },
    { label: 'Chungcheongbuk', value: '43' },
    { label: 'Chungcheongnam', value: '44' },
    { label: 'Jeollabuk', value: '45' },
    { label: 'Jeollanam', value: '46' },
    { label: 'Gyeongsangbuk', value: '47' },
    { label: 'Gyeongsangnam', value: '48' },
    { label: 'Jeju', value: '49' },
  ],

  // ── China ────────────────────────────────────────────────────────
  CN: [
    { label: 'Anhui', value: 'AH' },
    { label: 'Beijing', value: 'BJ' },
    { label: 'Chongqing', value: 'CQ' },
    { label: 'Fujian', value: 'FJ' },
    { label: 'Gansu', value: 'GS' },
    { label: 'Guangdong', value: 'GD' },
    { label: 'Guangxi', value: 'GX' },
    { label: 'Guizhou', value: 'GZ' },
    { label: 'Hainan', value: 'HI' },
    { label: 'Hebei', value: 'HE' },
    { label: 'Heilongjiang', value: 'HL' },
    { label: 'Henan', value: 'HA' },
    { label: 'Hubei', value: 'HB' },
    { label: 'Hunan', value: 'HN' },
    { label: 'Inner Mongolia', value: 'NM' },
    { label: 'Jiangsu', value: 'JS' },
    { label: 'Jiangxi', value: 'JX' },
    { label: 'Jilin', value: 'JL' },
    { label: 'Liaoning', value: 'LN' },
    { label: 'Ningxia', value: 'NX' },
    { label: 'Qinghai', value: 'QH' },
    { label: 'Shaanxi', value: 'SN' },
    { label: 'Shandong', value: 'SD' },
    { label: 'Shanghai', value: 'SH' },
    { label: 'Shanxi', value: 'SX' },
    { label: 'Sichuan', value: 'SC' },
    { label: 'Tianjin', value: 'TJ' },
    { label: 'Tibet', value: 'XZ' },
    { label: 'Xinjiang', value: 'XJ' },
    { label: 'Yunnan', value: 'YN' },
    { label: 'Zhejiang', value: 'ZJ' },
  ],

  // ── Switzerland ──────────────────────────────────────────────────
  CH: [
    { label: 'Aargau', value: 'AG' },
    { label: 'Appenzell Ausserrhoden', value: 'AR' },
    { label: 'Appenzell Innerrhoden', value: 'AI' },
    { label: 'Basel-Landschaft', value: 'BL' },
    { label: 'Basel-Stadt', value: 'BS' },
    { label: 'Bern', value: 'BE' },
    { label: 'Fribourg', value: 'FR' },
    { label: 'Genève', value: 'GE' },
    { label: 'Glarus', value: 'GL' },
    { label: 'Graubünden', value: 'GR' },
    { label: 'Jura', value: 'JU' },
    { label: 'Luzern', value: 'LU' },
    { label: 'Neuchâtel', value: 'NE' },
    { label: 'Nidwalden', value: 'NW' },
    { label: 'Obwalden', value: 'OW' },
    { label: 'Schaffhausen', value: 'SH' },
    { label: 'Schwyz', value: 'SZ' },
    { label: 'Solothurn', value: 'SO' },
    { label: 'St. Gallen', value: 'SG' },
    { label: 'Thurgau', value: 'TG' },
    { label: 'Ticino', value: 'TI' },
    { label: 'Uri', value: 'UR' },
    { label: 'Valais', value: 'VS' },
    { label: 'Vaud', value: 'VD' },
    { label: 'Zug', value: 'ZG' },
    { label: 'Zürich', value: 'ZH' },
  ],

  // ── Austria ──────────────────────────────────────────────────────
  AT: [
    { label: 'Burgenland', value: '1' },
    { label: 'Carinthia', value: '2' },
    { label: 'Lower Austria', value: '3' },
    { label: 'Salzburg', value: '5' },
    { label: 'Styria', value: '6' },
    { label: 'Tyrol', value: '7' },
    { label: 'Upper Austria', value: '4' },
    { label: 'Vienna', value: '9' },
    { label: 'Vorarlberg', value: '8' },
  ],

  // ── Poland ───────────────────────────────────────────────────────
  PL: [
    { label: 'Dolnośląskie', value: 'DS' },
    { label: 'Kujawsko-Pomorskie', value: 'KP' },
    { label: 'Lubelskie', value: 'LU' },
    { label: 'Lubuskie', value: 'LB' },
    { label: 'Łódzkie', value: 'LD' },
    { label: 'Małopolskie', value: 'MA' },
    { label: 'Mazowieckie', value: 'MZ' },
    { label: 'Opolskie', value: 'OP' },
    { label: 'Podkarpackie', value: 'PK' },
    { label: 'Podlaskie', value: 'PD' },
    { label: 'Pomorskie', value: 'PM' },
    { label: 'Śląskie', value: 'SL' },
    { label: 'Świętokrzyskie', value: 'SK' },
    { label: 'Warmińsko-Mazurskie', value: 'WN' },
    { label: 'Wielkopolskie', value: 'WP' },
    { label: 'Zachodniopomorskie', value: 'ZP' },
  ],
};

/**
 * Returns the subdivision options for a given country code,
 * or undefined if that country doesn't have predefined subdivisions
 * (meaning the form should fall back to a free-text input).
 */
export function getSubdivisionsForCountry(
  countryCode: string | undefined
): SubdivisionOption[] | undefined {
  if (!countryCode) return undefined;
  return COUNTRY_SUBDIVISIONS[countryCode as CountryCodeIsoAlpha2];
}
