import { defaultResources } from '@/i18n/config';
import { DefaultOptions } from '@tanstack/react-query';
import { DeepPartial } from 'react-hook-form';

export type EBColorScheme = 'dark' | 'light' | 'system';

export type EBThemeVariables = {
  fontFamily?: string;
  headerFontFamily?: string;
  buttonFontFamily?: string;
  backgroundColor?: string;
  foregroundColor?: string;
  borderRadius?: string;
  inputBorderRadius?: string;
  buttonBorderRadius?: string;
  buttonFontWeight?: string;
  buttonFontSize?: string;
  buttonLineHeight?: string;
  shiftButtonOnActive?: boolean;
  primaryButtonFontWeight?: string;
  secondaryButtonFontWeight?: string;
  destructiveButtonFontWeight?: string;
  primaryBorderWidth?: string;
  secondaryBorderWidth?: string;
  destructiveBorderWidth?: string;
  primaryColor?: string;
  primaryHoverColor?: string;
  primaryActiveColor?: string;
  primaryForegroundColor?: string;
  primaryForegroundHoverColor?: string;
  primaryForegroundActiveColor?: string;
  secondaryColor?: string;
  secondaryHoverColor?: string;
  secondaryActiveColor?: string;
  secondaryForegroundColor?: string;
  secondaryForegroundHoverColor?: string;
  secondaryForegroundActiveColor?: string;
  destructiveColor?: string;
  destructiveHoverColor?: string;
  destructiveActiveColor?: string;
  destructiveForegroundColor?: string;
  destructiveForegroundHoverColor?: string;
  destructiveForegroundActiveColor?: string;
  destructiveAccentColor?: string;
  informativeColor?: string;
  informativeAccentColor?: string;
  warningColor?: string;
  warningAccentColor?: string;
  successColor?: string;
  successAccentColor?: string;
  alertColor?: string;
  alertForegroundColor?: string;
  mutedColor?: string;
  mutedForegroundColor?: string;
  accentColor?: string;
  accentForegroundColor?: string;
  cardColor?: string;
  cardForegroundColor?: string;
  popoverColor?: string;
  popoverForegroundColor?: string;
  spacingUnit?: string;
  borderColor?: string;
  inputColor?: string;
  inputBorderColor?: string;
  ringColor?: string;
  zIndexOverlay?: number;
  buttonTextTransform?: string;
  buttonLetterSpacing?: string;
  formLabelFontSize?: string;
  formLabelFontWeight?: string;
  formLabelLineHeight?: string;
  formLabelForegroundColor?: string;
};

export type EBTheme = {
  colorScheme?: EBColorScheme;
  variables?: EBThemeVariables;
  light?: EBThemeVariables;
  dark?: EBThemeVariables;
};

export type EBConfig = {
  apiBaseUrl: string;
  theme?: EBTheme;
  headers?: Record<string, string>;
  reactQueryDefaultOptions?: DefaultOptions;
  contentTokens?: {
    name?: keyof typeof defaultResources;
    tokens?: DeepPartial<(typeof defaultResources)['enUS']>;
  };
  queryParams?: Record<string, string>;
};
