/* Editorial source of truth. Official guides reviewed 8 September 2026.
   J.P. Morgan is the bank identity; the town and activity are fictional examples. */
// @ts-nocheck
const SGContent = (() => {
  const base='https://developer.payments.jpmorgan.com';
  const ep='/docs/embedded-finance-solutions/embedded-payments';
  const checkout='/docs/commerce/online-payments/capabilities/checkout';
  const sources={
    overview:{label:'Embedded Payments overview',url:base+ep},
    onboarding:{label:'Client onboarding · official guide',url:base+'/api/llm-content?path='+encodeURIComponent('en/docs/embedded-finance-solutions/embedded-payments/capabilities/onboard-a-client/onboard-a-client1.md')},
    lifecycle:{label:'Complete onboarding & client statuses · official guide',url:base+'/api/llm-content?path='+encodeURIComponent('en/docs/embedded-finance-solutions/embedded-payments/capabilities/onboard-a-client/how-to/complete-onboarding-steps.md')},
    accounts:{label:'Account types & restrictions',url:base+ep+'/capabilities/accounts/account-setup/create-accounts'},
    concepts:{label:'Accounts, clients & linked accounts',url:base+ep+'/core-concepts'},
    checkout:{label:'Checkout overview · official guide',url:base+'/api/llm-content?path='+encodeURIComponent('en/docs/commerce/online-payments/capabilities/checkout/overview.md')},
    dropin:{label:'Drop-in UI',url:base+checkout+'/drop-in-ui'},
    hosted:{label:'Hosted Payment Page',url:base+checkout+'/hosted-payment'},
    link:{label:'Pay by Link',url:base+checkout+'/pay-by-link'},
    security:{label:'3-D Secure in Checkout',url:base+checkout+'/3ds-authentication'},
    fraud:{label:'Fraud prevention in Checkout',url:base+checkout+'/fraud-prevention'},
    payouts:{label:'Payout methods, timing & eligibility',url:base+ep+'/capabilities/transactions/payouts/overview'},
    events:{label:'Webhook events & delivery behavior · official guide',url:base+'/api/llm-content?path='+encodeURIComponent('en/docs/embedded-finance-solutions/embedded-payments/capabilities/notification-subscriptions/how-to/manage-notifications.md')},
    reports:{label:'Embedded Payments reports',url:base+ep+'/capabilities/reports/overview'}
  };
  const metaphor=[
    ['Town square','Your marketplace','The ecosystem in which your businesses operate.'],
    ['You, the mayor','Platform operator','You embed financial services in your platform.'],
    ['Town eras','Platform capabilities','Each chapter adds another capability to the ecosystem.'],
    ['Shops & stalls','Your clients','Sellers, vendors, and service providers.'],
    ['City Hall permits','Client onboarding / KYC','Business and related-party verification, due diligence, documents, and attestations.'],
    ['A vault under each shop','Client’s limited account','This story uses a LIMITED_DDA: funds are settled to the client’s linked account.'],
    ['Register & counter','Checkout','Drop-in UI, Hosted Payment Page, and Pay by Link are separately documented Checkout integrations.'],
    ['Lockbox & security gate','Tokenization, 3DS & fraud screening','Protect payment data and check transactions; the example is simplified.'],
    ['Train, express & courier','ACH, RTP & wire payouts','Available payment rails have different timing, setup, and eligibility.'],
    ['Home bank address','Linked external account','The client’s own verified external bank account, registered through recipients.'],
    ['City bell & notice board','Webhooks','Subscribed events tell the platform when statuses change.'],
    ['Prosperity board','Reporting & reconciliation','Connect account balances, transaction activity, and reports.'],
    ['J.P. Morgan tower','Financial infrastructure','J.P. Morgan represents the financial infrastructure behind the scene.']
  ];
  const storyCallouts=[
    {point:[450,355,20],title:'Your marketplace',description:'The town is the platform you run.'},
    {point:[207,138,125],title:'City Hall',description:'A permit stands for business verification.'},
    {point:[215,425,115],title:'The shops',description:'Each shop is one business client.'},
    {point:[230,525,55],title:'The vault',description:'An account gives a client a place to manage funds.'},
    {point:[315,520,67],title:'The register',description:'Checkout lets customers pay.'},
    {point:[760,570,40],title:'The routes',description:'Eligible payouts travel by RTP, ACH, or wire.'},
    {point:[590,110,230],title:'J.P. Morgan tower',description:'Financial infrastructure supports the town.'}
  ];
  const step=(at,key,label,summary,narration,callout,term,detail,refs,focus)=>({at,key,label,summary,narration,callout,term,detail,refs,focus});
  const chapters=[
    {name:'Welcome',title:'Build a thriving marketplace.',category:'THE OBJECTIVE',premise:'You run the town. You don’t have to build the bank.',era:'Quiet Square',duration:20,benefit:'Help every business join, hold funds, accept payments, and get paid.',note:'A three-minute story. No clicks needed.',steps:[
      step(0,'objective','You are the mayor','Your town is a marketplace.','Your goal: turn a quiet square into a thriving marketplace.','Your platform starts here','Town square → Marketplace','You are the platform operator. Shops represent your business clients; the J.P. Morgan tower represents financial infrastructure. The town and its businesses are fictional examples.',['overview'],'wide'),
      step(7,'journey','Grow one capability at a time','Verify. Manage. Accept. Transfer.','Each new capability helps Rosie’s business take its next step.','One connected foundation','Town eras → Capabilities','Watch one business progress through onboarding, an account, checkout, and payout. The additional businesses arrive only in the final chapter. Checkout is a separately documented product.',['overview','checkout'],'wide'),
      step(14,'metaphor','Learn the town’s language','Permits, vaults, registers & rails.','Permits mean verification. Vaults mean accounts. Vehicles mean payouts.','A town built on a simple idea','Town objects → Financial services','The metaphor makes a financial journey visible. It compresses time and shows one successful example, without promising an outcome or a service speed. Open “Story & metaphor” for the full map.',['overview','concepts'],'wide')
    ]},
    {name:'Onboard',title:'Open the doors.',category:'CLIENT ONBOARDING',premise:'Rosie’s Bakery wants to set up shop.',era:'Trusted Merchants',duration:35,benefit:'A digital onboarding journey, with verification and due diligence built in.',note:'Example approval journey. Reviews and outcomes vary.',steps:[
      step(0,'application','Rosie arrives at City Hall','Create her business & party profiles.','Rosie brings her business details and information about the people behind it.','Application received','Client status · NEW','Create the client profile and related parties, including the people who represent and own the business. NEW means verification has not started; it is not an approval.',['onboarding','lifecycle'],'hall'),
      step(5,'requirements','Complete the application','Questions, documents & attestations.','Business details. Owner ID. Due diligence answers. Required attestations.','Complete the application','Outstanding onboarding requirements','Collect the outstanding information returned for the client and related parties. Request and submit required documents, answer due diligence questions, and capture required attestations before requesting verification.',['onboarding','lifecycle'],'hall'),
      step(11,'review','The review begins','Verification is now in progress.','City Hall checks Rosie’s application and the people behind the business.','Under review','Client status · REVIEW_IN_PROGRESS','Submitting the verification request starts the required checks. An accepted request is not an approved client. Both the client and associated parties must complete onboarding.',['lifecycle'],'hall'),
      step(17,'missing','One more document','A request to continue, not a rejection.','One document is missing. Rosie is asked to send it so the review can continue.','One more document, Rosie','Client status · INFORMATION_REQUESTED','Additional information or documents may be required for the client or a related party. This is a recoverable step in the example, not a guarantee of eventual approval.',['lifecycle'],'hall'),
      step(23,'resubmit','Rosie sends it in','The application returns to review.','Rosie supplies the document. Her application goes back into review.','Document received. Reviewing…','Client status · REVIEW_IN_PROGRESS','After the requested information is supplied, the documented client status returns to REVIEW_IN_PROGRESS. Only a subsequent APPROVED result completes this example.',['lifecycle'],'hall'),
      step(29,'approved','Approved. Doors open.','Now the bakery can join the town.','Rosie and her related parties are approved. Let’s build the bakery!','Welcome to the neighborhood','Client status · APPROVED','This approval indicates the client and associated parties completed due diligence. The story now constructs the bakery. The actual lifecycle also includes declined, suspended, and terminated states; approval is not guaranteed.',['lifecycle'],'bakery')
    ]},
    {name:'Manage',title:'A vault of her own.',category:'MANAGE FUNDS',premise:'Rosie needs a home for her business funds.',era:'Account-ready Stalls',duration:25,benefit:'An account for each onboarded business, with balances visible in your platform.',note:'This story follows the Limited DDA account model.',steps:[
      step(0,'account','Create Rosie’s account','Approval comes before the vault.','With onboarding complete, Rosie’s own limited account can be created.','An account for Rosie','Shop vault → Limited DDA','A Limited DDA can be created after client onboarding. Optional automatic account creation is available by arrangement; the animation does not imply it is enabled for every platform.',['accounts'],'bakery'),
      step(7,'ownership','Put her name on it','Keep each business’s funds identifiable.','This vault belongs to Rosie’s business, with its own account record.','Rosie’s Bakery · Own account','Limited account → Client’s name & Tax ID','Limited accounts are in the client’s own name and Tax ID. They are distinct from virtual transaction accounts beneath a physical DDA. This story consistently follows a LIMITED_DDA.',['accounts','concepts'],'bakery'),
      step(14,'balance','Read the balance','Ready at $0.','Rosie’s balance starts at zero. The platform can display it as funds arrive.','Balance · $0','Vault ledger → Account balance','The platform can retrieve and display the account balance. A balance is not a promise that the client can freely spend the funds: Limited DDA funds remain subject to settlement to a linked account.',['accounts','concepts'],'bakery'),
      step(20,'ready','Connect the money grid','Ready for platform settlement.','Her account is ready to receive funds allocated by the platform.','Ready for incoming funds','Golden pipe → Platform funding','A standard LIMITED_DDA is not externally addressable. The platform can settle funds into it. The next chapter separates the customer checkout from this later funding step.',['accounts'],'bakery')
    ]},
    {name:'Accept',title:'Ring the register.',category:'ACCEPT PAYMENTS · CHECKOUT',premise:'Rosie is ready to sell — online and everywhere.',era:'Open Market',duration:35,benefit:'Give customers ways to pay, with payment security behind the storefront.',note:'Checkout is separate from Embedded Payments. Settlement is a later step.',steps:[
      step(0,'dropin','Pay at the built-in counter','A form on Rosie’s own website.','A $1,500 catering order is paid on Rosie’s page using Drop-in UI.','Pay on Rosie’s page','Built-in counter → Drop-in UI','Drop-in UI is a JavaScript payment form embedded in the merchant’s page. It collects, encrypts, and transfers payment data to the payment provider. This counter represents online checkout, not a physical point-of-sale terminal.',['dropin','checkout'],'bakery'),
      step(5,'hosted','Visit the ready-made stall','A hosted payment page.','A $2,500 office breakfast order uses a hosted payment page.','A ready-made payment page','Market stall → Hosted Payment Page','Hosted Payment Page redirects the customer from the merchant’s website to a provider-hosted payment experience. It is another way to integrate Checkout.',['hosted','checkout'],'bakery'),
      step(10,'link','Follow a payment link','A link received by email or text.','A $4,500 event order is paid through a link on the customer’s phone.','A link. An order. A payment.','Delivery coupon → Pay by Link','Pay by Link lets the merchant share a payment link through email or text. The animation uses three illustrative catering orders: $1,500 + $2,500 + $4,500 = $8,500 to show the three integration choices.',['link','checkout'],'bakery'),
      step(15,'token','Protect the payment data','The card becomes a lockbox.','A token stands in for the card details. Rosie’s shop uses the token.','Card details → Token','Lockbox → Tokenization','Checkout offers Safetech and Network tokenization. A token represents payment data; it should not be described as universally useless if stolen or as eliminating all PCI responsibilities.',['checkout'],'bakery'),
      step(20,'identity','Confirm identity when needed','An example 3-D Secure check.','When a challenge is needed, the customer confirms their identity.','Identity check completed','Security check → 3-D Secure','3-D Secure supports cardholder authentication. Some payments are frictionless and some require a challenge. A phone confirmation is one simplified example, not a required step for every purchase.',['security','checkout'],'bakery'),
      step(25,'screen','Screen suspicious activity','A risky visitor is stopped at the gate.','Fraud screening checks the payment. This suspicious attempt is stopped.','Suspicious attempt stopped','Security gate → Fraud screening','The example shows a blocked attempt. Screening can help assess risk; it does not guarantee every fraudulent transaction is detected. The earlier example orders are separate from this stopped attempt.',['fraud','checkout'],'bakery'),
      step(30,'settle','Later: settle & allocate funds','Checkout success comes first.','Later, after settlement, the platform allocates $8,500 to Rosie’s account.','Later · Funds allocated','Platform settlement → Limited account','A successful checkout is not an instant credit to a Limited DDA. Processing accounts can receive merchant-acquirer settlements and allocate funds to clients. This compressed scene illustrates a configured flow, with $8,500 of catering orders and no fees or refunds modeled.',['accounts','checkout'],'bakery')
    ]},
    {name:'Transfer',title:'Money in motion.',category:'TRANSFER FUNDS',premise:'Rosie wants her earnings in her own bank.',era:'Connected Market',duration:30,benefit:'Choose an available payment rail for the need, then track the payout.',note:'Rail availability, cutoffs and limits apply. Travel time is illustrative.',steps:[
      step(0,'linked','Save her home bank address','Link and validate Rosie’s own account.','The town saves Rosie’s verified home bank details for payouts.','Rosie’s home bank · Linked','Home bank → LINKED_ACCOUNT','For this Limited DDA example, payouts go to the client’s own linked external account. The recipients resource registers the linked account, with ownership validation as part of setup.',['concepts','payouts'],'payout'),
      step(6,'rtp','Take the express route','RTP · Real-time, when eligible.','Three payouts depart. The $2,000 RTP example reaches Rosie’s bank first.','Express · Real-time payments','Express → RTP','The payout guide lists RTP as immediate with no cutoff, subject to enabled payment methods, eligible account details, limits, and receiving-bank support. The example does not promise a fee.',['payouts'],'payout'),
      step(12,'ach','Send the scheduled train','ACH · 1–2 business days.','Another $3,000 travels by ACH. The guide lists one to two business days.','Cargo train · ACH','Train → ACH','The guide lists U.S. ACH settlement at 1–2 business days, subject to its business-day cutoff and configuration. A train’s travel time is a metaphor, not a live delivery estimate.',['payouts'],'payout'),
      step(18,'wire','Choose the courier','Wire · Same business day, within cutoff.','The final $3,500 illustrates a wire to Rosie’s own linked bank account.','Courier · Wire','Armored courier → Wire','The guide lists U.S. wire settlement on the same business day, within its cutoff. These illustrative payouts compare rails. Paying an oven supplier from a standard LIMITED_DDA would be incorrect: third-party payments require an eligible account model such as LIMITED_DDA_PAYMENTS.',['payouts','accounts'],'payout'),
      step(24,'delivered','Check the result','Submitted and completed are different.','Later, completion updates confirm the payouts. Rosie’s $8,500 has moved home; her town account is now empty.','Payouts completed','Delivery notice → Transaction status','A submitted payout is not necessarily completed. Subscribed transaction notifications and transaction queries support tracking success or failure. The example debits $8,500 when all three payouts depart, then tracks it in transit until receipt. $2,000 + $3,000 + $3,500 = $8,500. No fees or opening home-bank balance are modeled. The example compresses all three settlements into one scene.',['payouts','events'],'payout')
    ]},
    {name:'Thrive',title:'The town grows together.',category:'SCALE & AUTOMATION',premise:'Word has spread. Four more businesses want to join.',era:'Thriving Bazaar',duration:35,benefit:'Repeat the journey for more businesses, with event updates and reporting.',note:'Illustrative activity. The same checks still apply as the town grows.',steps:[
      step(0,'arrivals','Four new ideas arrive','A florist, gym, bookshop & coffee cart.','Four more businesses apply. Each starts the same onboarding journey.','Four new applications','New shops → More clients','The florist, gym, bookshop, and coffee business first arrive in this chapter. More clients still require onboarding; growth does not bypass due diligence.',['onboarding'],'wide'),
      step(6,'expand','Approved businesses open','Now the new shops are built.','After their example approvals, the new businesses open their doors.','Welcome, new neighbors','Permit approvals → Client onboarding','This montage compresses successful example reviews. Each business and its associated parties must satisfy the required onboarding checks.',['lifecycle'],'wide'),
      step(12,'new-accounts','Give each one an account','Their own vaults. Their own records.','Every new business gets an account after approval.','Five businesses. Five accounts.','Shop vaults → Limited accounts','The town repeats the limited-account journey for the four additional clients. Account creation may be requested by the platform or configured to occur automatically.',['accounts'],'wide'),
      step(18,'activity','Registers ring. Payouts roll.','Repeat the connected journey.','More customers buy. Settlements and payouts follow their own timelines.','A marketplace in motion','Town activity → Payment journeys','Each business can use the separately configured Checkout experience, receive platform funding, and use eligible payouts. This montage does not imply immediate settlement or unrestricted third-party payouts.',['checkout','payouts'],'wide'),
      step(24,'events','The town keeps you informed','The bell rings. The board updates.','The city bell announces an approval, an account creation, and a completed payout.','The town tells you what changed','City bell → Webhooks','Subscribe to client, account, recipient, and transaction events. Webhooks can be duplicated or arrive out of order; applications must handle both. Reporting and balance queries help with reconciliation.',['events','reports'],'wide'),
      step(30,'recap','See the whole picture','One town. A connected ecosystem.','Your marketplace. Your businesses. Financial capabilities built into the journey.','From quiet square to thriving bazaar','Prosperity board → Reporting','The recap maps every town object to its real capability. Embedded Payments supports onboarding, accounts, money movement, payouts, and reporting; Checkout is an adjacent integration. Dusk returns the story to the opening objective.',['overview','reports','checkout'],'wide')
    ]}
  ];
  return {sources,metaphor,storyCallouts,chapters,reviewed:'2026-09-08',labels:{bakery:'ROSIE’S BAKERY',florist:'BLOOM & CO.',coffee:'DAILY BREW',books:'THE BOOK NOOK',gym:'GOOD FORM',hall:'CITY HALL',bank:'J.P. MORGAN',homebank:'HOME BANK'},
    objective:{title:'A small town. A shared ambition.',body:'Grow a quiet marketplace into a thriving bazaar by helping businesses join, manage their money, accept online payments, and get paid.',role:'You are the mayor — the platform operator.',rules:['The town runs itself. Watch the story, or choose a chapter.','Every business completes onboarding before its account opens.','Payment acceptance, account funding, and payout are separate steps.','Success means a connected marketplace with every business accounted for.']}};
})();

export default SGContent;
