import { OrganizationType } from '@/api/generated/smbdo.schemas';

export const ORGANIZATION_TYPE_LIST: OrganizationType[] = [
  'LIMITED_LIABILITY_COMPANY',
  'LIMITED_LIABILITY_PARTNERSHIP',
  'GENERAL_PARTNERSHIP',
  'LIMITED_PARTNERSHIP',
  'C_CORPORATION',
  'S_CORPORATION',
  'PARTNERSHIP',
  'PUBLICLY_TRADED_COMPANY',
  'NON_PROFIT_CORPORATION',
  'GOVERNMENT_ENTITY',
  'SOLE_PROPRIETORSHIP',
  'UNINCORPORATED_ASSOCIATION',
];
